from .linear_regression.py_interface.linear_regression_python import LinearRegressionPython
from .linear_regression.py_interface.linear_regression_c import LinearRegressionC
from .classical_model import ClassicalModel